# Generated by Django 2.1.1 on 2018-09-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180916_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='language',
        ),
    ]
