# Generated by Django 2.1.1 on 2018-10-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_answer_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
    ]
