# Generated by Django 2.1.1 on 2018-10-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20181002_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='language',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='text',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.AddField(
            model_name='announcement',
            name='text_kaz',
            field=models.TextField(default='s', verbose_name='текст(kaz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='text_rus',
            field=models.TextField(default='r', verbose_name='текст(rus)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_kaz',
            field=models.TextField(default='tt', verbose_name='название(kaz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_rus',
            field=models.TextField(default='ww', verbose_name='название(rus)'),
            preserve_default=False,
        ),
    ]
