# Generated by Django 2.1.1 on 2018-10-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_calcparameters'),
        ('news', '0009_auto_20181006_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_kaz',
            field=models.TextField(default='zhauap', verbose_name='ответ(kaz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_rus',
            field=models.TextField(default='otvet', verbose_name='ответ(rus)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_kaz',
            field=models.TextField(default='surak', verbose_name='вопрос(kaz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_rus',
            field=models.TextField(default='vopros', verbose_name='вопрос(rus)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
