# Generated by Django 2.1.1 on 2018-10-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20181007_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='service',
        ),
    ]
