# Generated by Django 2.1.1 on 2018-10-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_question_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='icon',
            field=models.ImageField(default='notif_images/icon.png', upload_to='notif_images'),
            preserve_default=False,
        ),
    ]
