# Generated by Django 2.1.1 on 2018-10-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20181008_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='на главную'),
        ),
    ]
