# Generated by Django 2.1.1 on 2018-10-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_news_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_thumbnails'),
        ),
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news_thumbnails'),
        ),
    ]
