# Generated by Django 2.1.1 on 2018-09-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.TextField(null=True, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Language', verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(verbose_name='название'),
        ),
    ]
