# Generated by Django 2.1.1 on 2018-09-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
