# Generated by Django 2.1.1 on 2018-10-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_address_companyinfo_coordinate_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinate',
            options={'verbose_name': 'координаты', 'verbose_name_plural': 'координаты'},
        ),
        migrations.AddField(
            model_name='address',
            name='address_kaz',
            field=models.CharField(default='test', max_length=256, verbose_name='адрес(kaz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='address_rus',
            field=models.CharField(default='test', max_length=256, verbose_name='адрес(rus)'),
            preserve_default=False,
        ),
    ]
