# Generated by Django 2.1.1 on 2018-10-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181011_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_kaz', models.CharField(max_length=256, verbose_name='адрес(kaz)')),
                ('text_rus', models.CharField(max_length=256, verbose_name='адрес(rus)')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_num', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чат'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_kaz',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_rus',
        ),
        migrations.RemoveField(
            model_name='address',
            name='buses',
        ),
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.AddField(
            model_name='mail',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='main.Address', verbose_name='email'),
        ),
        migrations.AddField(
            model_name='bus',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='main.Address', verbose_name='автобус'),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='main.Address', verbose_name='адрес'),
        ),
    ]
