# Generated by Django 2.1.1 on 2018-10-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181012_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressinfo',
            options={'verbose_name': 'адрес', 'verbose_name_plural': 'адрес'},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'автобус', 'verbose_name_plural': 'автобусы'},
        ),
        migrations.AlterModelOptions(
            name='coordinate',
            options={'verbose_name': 'координата', 'verbose_name_plural': 'координаты'},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'email', 'verbose_name_plural': 'email'},
        ),
        migrations.AlterField(
            model_name='bus',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='main.Address', verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_num',
            field=models.CharField(max_length=8, verbose_name='автобус'),
        ),
    ]
