# Generated by Django 2.1.1 on 2018-11-02 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_chatroom_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTaxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=64, verbose_name='телефон')),
                ('telephone_title_rus', models.CharField(max_length=264, verbose_name='название такси(rus)')),
                ('telephone_title_kaz', models.CharField(max_length=264, verbose_name='название такси(kaz)')),
            ],
        ),
        migrations.CreateModel(
            name='TaxiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_kaz', models.TextField()),
                ('text_rus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxiQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_kaz', models.TextField(verbose_name='вопрос(kaz)')),
                ('question_rus', models.TextField(verbose_name='вопрос(rus)')),
                ('answer_kaz', models.TextField(verbose_name='ответ(kaz)')),
                ('answer_rus', models.TextField(verbose_name='ответ(rus)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'вопрос(Такси)',
                'verbose_name_plural': 'вопросы(Такси)',
            },
        ),
        migrations.AddField(
            model_name='phonetaxi',
            name='taxi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='main.TaxiInfo', verbose_name='такси'),
        ),
    ]
