# Generated by Django 2.1.1 on 2018-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181102_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxiquestion',
            options={'verbose_name': 'Такси(Вопрос)', 'verbose_name_plural': 'Такси(Вопросы)'},
        ),
        migrations.AddField(
            model_name='taxiinfo',
            name='icon',
            field=models.ImageField(default='taxi_icon/icon.png', upload_to='taxi_icon'),
            preserve_default=False,
        ),
    ]
