# Generated by Django 2.1.1 on 2018-11-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181102_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxiinfo',
            options={'verbose_name': 'Такси', 'verbose_name_plural': 'Такси'},
        ),
        migrations.AddField(
            model_name='taxiinfo',
            name='title_kaz',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxiinfo',
            name='title_rus',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxiinfo',
            name='text_kaz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taxiinfo',
            name='text_rus',
            field=models.TextField(null=True),
        ),
    ]
