# Generated by Django 2.1.1 on 2018-11-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_taxiimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='icon',
            field=models.ImageField(default='/media/1.png', upload_to='about'),
            preserve_default=False,
        ),
    ]
