# Generated by Django 2.1.1 on 2018-09-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_default_langs'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='subservice',
            options={'verbose_name': 'Суб-Услуги', 'verbose_name_plural': 'Суб-Услуги'},
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Language', verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='service',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Language', verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Language', verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='services.SubService', verbose_name='cуб-услуга'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='ntrcn'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='services.Service', verbose_name='услуга'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='title',
            field=models.TextField(verbose_name='название'),
        ),
    ]
