# Generated by Django 2.1.1 on 2018-09-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180916_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='service',
        ),
        migrations.AddField(
            model_name='post',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='services.Service', verbose_name='услуга'),
            preserve_default=False,
        ),
    ]
