# Generated by Django 2.1.1 on 2018-09-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180916_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Title',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Title', verbose_name='название'),
        ),
    ]
