# Generated by Django 2.1.1 on 2018-09-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180924_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='language',
        ),
    ]
