# Generated by Django 2.1.1 on 2018-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20180924_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='title',
            field=models.TextField(unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.TextField(unique=True, verbose_name='текст'),
        ),
    ]
