# Generated by Django 2.1.1 on 2018-09-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20180924_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='services.Title', verbose_name='название'),
        ),
    ]
