# Generated by Django 2.1.1 on 2018-10-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20180925_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_kaz',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='title_kaz',
        ),
        migrations.RenameField(
            model_name='subservice',
            old_name='title',
            new_name='title_kaz',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='name',
            new_name='name_kaz',
        ),
        migrations.RemoveField(
            model_name='service',
            name='language',
        ),
        migrations.AddField(
            model_name='post',
            name='text_rus',
            field=models.TextField(default='something', verbose_name='текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_rus',
            field=models.TextField(default='bla blaa', unique=True, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subservice',
            name='title_rus',
            field=models.TextField(default='agaga', unique=True, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='name_rus',
            field=models.TextField(default='adasd', unique=True, verbose_name='текст'),
            preserve_default=False,
        ),
    ]
