# Generated by Django 2.1.1 on 2018-10-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20181005_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Заглавие', 'verbose_name_plural': 'Заглавие'},
        ),
        migrations.AlterField(
            model_name='post',
            name='text_kaz',
            field=models.TextField(verbose_name='текст(kaz)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_rus',
            field=models.TextField(verbose_name='текст(rus)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='services.Title', verbose_name='заглавие'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_kaz',
            field=models.TextField(unique=True, verbose_name='название(kaz)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_rus',
            field=models.TextField(unique=True, verbose_name='название(rus)'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='title_kaz',
            field=models.TextField(unique=True, verbose_name='название(kaz)'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='title_rus',
            field=models.TextField(unique=True, verbose_name='название(rus)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name_kaz',
            field=models.TextField(unique=True, verbose_name='название(kaz)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name_rus',
            field=models.TextField(unique=True, verbose_name='название(rus)'),
        ),
    ]
