# Generated by Django 2.1.1 on 2018-10-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20181006_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(default='icon', upload_to='media'),
            preserve_default=False,
        ),
    ]
