# Generated by Django 2.1.1 on 2018-10-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
