# Generated by Django 2.1.1 on 2018-10-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_subservice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
