# Generated by Django 2.1.1 on 2018-10-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20181006_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='title',
            name='order_in_list',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='порядок'),
        ),
    ]
