# Generated by Django 2.1.1 on 2018-10-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20181006_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='параметр')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='значение')),
            ],
        ),
    ]
