# Generated by Django 2.1.1 on 2018-10-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_calcparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_kaz', models.TextField(verbose_name='вопрос(kaz)')),
                ('question_rus', models.TextField(verbose_name='вопрос(rus)')),
                ('answer_kaz', models.TextField(verbose_name='ответ(kaz)')),
                ('answer_rus', models.TextField(verbose_name='ответ(rus)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'вопрос(Калькулятор)',
                'verbose_name_plural': 'вопросы(Калькулятор)',
            },
        ),
        migrations.RenameModel(
            old_name='CalcParameters',
            new_name='CalcParameter',
        ),
    ]
