# Generated by Django 2.1.1 on 2018-10-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='my_city_images', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.CreateModel(
            name='CityNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kaz', models.TextField(verbose_name='название(kaz)')),
                ('title_rus', models.TextField(verbose_name='название(rus)')),
                ('text_kaz', models.TextField(verbose_name='текст(kaz)')),
                ('text_rus', models.TextField(verbose_name='текст(rus)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Мой Город',
                'verbose_name_plural': 'Мой Город',
            },
        ),
        migrations.CreateModel(
            name='CityVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField(max_length=150, verbose_name='видео')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='my_city.CityNews', verbose_name='видео')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видео',
            },
        ),
        migrations.AddField(
            model_name='cityimage',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='my_city.CityNews', verbose_name='изображение'),
        ),
    ]
