# Generated by Django 2.1.1 on 2018-10-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_city', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityvideo',
            old_name='icon',
            new_name='url',
        ),
    ]
