# Generated by Django 2.1.1 on 2018-10-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_city', '0002_auto_20181012_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityvideo',
            name='news',
        ),
        migrations.AddField(
            model_name='citynews',
            name='video_url',
            field=models.URLField(max_length=150, null=True, verbose_name='видео'),
        ),
        migrations.DeleteModel(
            name='CityVideo',
        ),
    ]
