# Generated by Django 2.1.1 on 2018-10-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_city', '0003_auto_20181013_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citynews',
            name='video_url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='видео'),
        ),
    ]
