# Generated by Django 2.1.1 on 2018-10-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_city', '0004_auto_20181013_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='citynews',
            name='video_screenshot',
            field=models.ImageField(default='my_city_video_screens/icon.png', upload_to='my_city_video_screens', verbose_name='скриншот видео'),
            preserve_default=False,
        ),
    ]
