# Generated by Django 2.1.1 on 2018-10-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_city', '0005_citynews_video_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citynews',
            name='video_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='my_city_video_screens', verbose_name='скриншот видео'),
        ),
    ]
