# Generated by Django 2.1.1 on 2018-10-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_city', '0006_auto_20181013_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='citynews',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
